# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asistentes',
            fields=[
                ('idasis', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
        migrations.CreateModel(
            name='EstadoReunion',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEstado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificador', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Reunion',
                'verbose_name_plural': 'Estado Reuniones',
            },
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('IdEstadoTarea', models.AutoField(primary_key=True, serialize=False)),
                ('NomEstadoTar', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('idLugar', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('Estado', models.CharField(choices=[('S', 'Disponible'), ('N', 'No Disponible')], max_length=1, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificador', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('IdReunion', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero de Citacion')),
                ('organizador', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('tiempo_estimado', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Numero de Horas', null=True)),
                ('asunto', models.CharField(max_length=100)),
                ('hora_final', models.TimeField(help_text='HH24:MM:SS')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificador', models.CharField(max_length=50)),
                ('idEstado', models.ForeignKey(blank=True, default='', max_length=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.EstadoReunion')),
                ('idLugar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Lugar')),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reuniones',
            },
        ),
        migrations.CreateModel(
            name='temasdos',
            fields=[
                ('tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Tema')),
                ('Contenido', models.TextField(blank=True, max_length=4000, null=True)),
                ('Acuerdos', models.TextField(blank=True, max_length=4000, null=True)),
                ('idreunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Reuniones')),
                ('tema_padre_dos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.temasdos', verbose_name='Tema a Asociar')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='TipoReunion',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_creador', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_modificador', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Reunion',
                'verbose_name_plural': 'Tipos Reuniones',
            },
        ),
        migrations.AddField(
            model_name='reuniones',
            name='idTipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.TipoReunion'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='idReunion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Reuniones'),
        ),
        migrations.AddField(
            model_name='asistentes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asistente'),
        ),
    ]
